import { useCallback, useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import type { IssuePriority, IssueStatus } from "@/lib/demo-data";

export const BUCKET = "issue-images";
export const ACCEPTED_IMAGE_TYPES = ["image/jpeg", "image/jpg", "image/png", "image/webp"];
export const ACCEPTED_DOC_TYPES = ["application/pdf"];
export const ACCEPTED_TYPES = [...ACCEPTED_IMAGE_TYPES, ...ACCEPTED_DOC_TYPES];
export const MAX_FILE_BYTES = 10 * 1024 * 1024; // 10 MB
export const MAX_FILES = 4;

// Backwards-compatible aliases
export const MAX_IMAGE_BYTES = MAX_FILE_BYTES;

export interface Attachment {
  path: string;
  name: string;
  type: string;
}

export function isImageType(type: string): boolean {
  return ACCEPTED_IMAGE_TYPES.includes(type.toLowerCase());
}

export interface IssueRow {
  id: string;
  ticket_id: string;
  user_id: string;
  title: string;
  category: string;
  priority: IssuePriority;
  description: string;
  location: string | null;
  image_url: string | null;
  attachments: Attachment[];
  status: IssueStatus;
  created_at: string;
  updated_at: string;
}

export interface IssueStats {
  total: number;
  pending: number;
  in_progress: number;
  resolved: number;
  today: number;
}

export interface NewIssueInput {
  title: string;
  category: string;
  priority: IssuePriority;
  description: string;
  location: string;
}

export function validateImageFile(file: File): string | null {
  const type = file.type.toLowerCase();
  if (!ACCEPTED_TYPES.includes(type)) {
    return "Unsupported file type. Use JPG, PNG or WEBP.";
  }
  if (file.size > MAX_IMAGE_BYTES) {
    return "Image is too large. Maximum size is 10 MB.";
  }
  return null;
}

// Upload one image into the user's folder; returns the storage path.
export async function uploadIssueImage(file: File): Promise<string> {
  const { data: userData, error: userErr } = await supabase.auth.getUser();
  if (userErr || !userData.user) throw new Error("You must be signed in to upload.");

  const ext = file.name.split(".").pop()?.toLowerCase() || "jpg";
  const path = `${userData.user.id}/${crypto.randomUUID()}.${ext}`;

  const { error } = await supabase.storage.from(BUCKET).upload(path, file, {
    cacheControl: "3600",
    upsert: false,
    contentType: file.type,
  });
  if (error) throw error;
  return path;
}

export async function removeIssueImage(path: string): Promise<void> {
  await supabase.storage.from(BUCKET).remove([path]);
}

// Generate a signed URL for a stored image path (private bucket).
export async function getSignedImageUrl(path: string): Promise<string | null> {
  const { data, error } = await supabase.storage
    .from(BUCKET)
    .createSignedUrl(path, 60 * 60);
  if (error) return null;
  return data?.signedUrl ?? null;
}

export async function createIssue(input: NewIssueInput, imagePath: string | null): Promise<IssueRow> {
  const { data: userData, error: userErr } = await supabase.auth.getUser();
  if (userErr || !userData.user) throw new Error("You must be signed in to report an issue.");

  const { data, error } = await supabase
    .from("issues")
    .insert({
      ticket_id: "", // generated by DB trigger
      user_id: userData.user.id,
      title: input.title.trim(),
      category: input.category,
      priority: input.priority,
      description: input.description.trim(),
      location: input.location.trim() || null,
      image_url: imagePath,
    })
    .select()
    .single();

  if (error) throw error;
  return data as IssueRow;
}

export async function getIssueByTicket(ticket: string) {
  const { data, error } = await supabase.rpc("get_issue_by_ticket", {
    _ticket: ticket,
  });
  if (error) throw error;
  return (data && data[0]) || null;
}

// ---- Hooks ----

export function useIssueStats() {
  const [stats, setStats] = useState<IssueStats | null>(null);
  const [loading, setLoading] = useState(true);

  const load = useCallback(async () => {
    const { data, error } = await supabase.rpc("get_issue_stats");
    if (!error && data) {
      setStats(data as unknown as IssueStats);
    }
    setLoading(false);
  }, []);

  useEffect(() => {
    load();
    const channel = supabase
      .channel("issue-stats")
      .on("postgres_changes", { event: "*", schema: "public", table: "issues" }, () => load())
      .subscribe();
    return () => {
      supabase.removeChannel(channel);
    };
  }, [load]);

  return { stats, loading };
}

export function useMyIssues() {
  const [issues, setIssues] = useState<IssueRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    const { data: userData } = await supabase.auth.getUser();
    if (!userData.user) {
      setIssues([]);
      setLoading(false);
      return;
    }
    const { data, error } = await supabase
      .from("issues")
      .select("*")
      .eq("user_id", userData.user.id)
      .order("created_at", { ascending: false });
    if (error) {
      setError(error.message);
    } else {
      setIssues((data as IssueRow[]) ?? []);
      setError(null);
    }
    setLoading(false);
  }, []);

  useEffect(() => {
    load();
    const channel = supabase
      .channel("my-issues")
      .on("postgres_changes", { event: "*", schema: "public", table: "issues" }, () => load())
      .subscribe();
    return () => {
      supabase.removeChannel(channel);
    };
  }, [load]);

  return { issues, loading, error, reload: load };
}

export function useAllIssues(enabled: boolean) {
  const [issues, setIssues] = useState<IssueRow[]>([]);
  const [loading, setLoading] = useState(true);

  const load = useCallback(async () => {
    if (!enabled) return;
    const { data, error } = await supabase
      .from("issues")
      .select("*")
      .order("created_at", { ascending: false });
    if (!error) setIssues((data as IssueRow[]) ?? []);
    setLoading(false);
  }, [enabled]);

  useEffect(() => {
    if (!enabled) return;
    load();
    const channel = supabase
      .channel("all-issues")
      .on("postgres_changes", { event: "*", schema: "public", table: "issues" }, () => load())
      .subscribe();
    return () => {
      supabase.removeChannel(channel);
    };
  }, [enabled, load]);

  return { issues, loading, reload: load };
}
